
-- +migrate Up
CREATE TABLE IF NOT EXISTS "BOOK"(
    ID SERIAL PRIMARY KEY,
    ISBN CHAR(5) NOT NULL UNIQUE,
    TITLE VARCHAR(200) NOT NULL,
    AUTHOR VARCHAR(100) NOT NULL,
    AVAILABLE INT DEFAULT 0,
    BORROWED INT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- +migrate Down
DROP TABLE IF EXISTS "BOOK";

