
-- +migrate Up
CREATE TABLE IF NOT EXISTS "USER"(
    ID SERIAL PRIMARY KEY,
    NAME varchar(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    ROLE USER_ROLE NOT NULL,
    APPROVED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- +migrate Down
DROP TABLE IF EXISTS "USER";

