
-- +migrate Up
CREATE TABLE IF NOT EXISTS "BORROWED"(
    ID SERIAL PRIMARY KEY,
    USER_ID INT not null,
    BOOK_ID INT not null,
    PROGRESS INT DEFAULT 0,
    RETURNED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- +migrate Down
DROP TABLE IF EXISTS "BORROWED";

